<?php
$securesecret=\Magento\Framework\App\ObjectManager::getInstance()->get('Ozi\Securecommanbank\Helper\Data')->getSecureHash();
$redirectURL = \Magento\Framework\App\ObjectManager::getInstance()->get('Ozi\Securecommanbank\Helper\Data')->getRedirectUrl();
$postdata = \Magento\Framework\App\ObjectManager::getInstance()->get('Ozi\Securecommanbank\Model\PaymentconnectionFactory')->create()->getPostData();
?>
<form id="order-migs" name="order" action="<?php echo($redirectURL); ?>" method="post">
    <!-- input type="submit" name="submit" value="Continue"/ -->
    <p>Please wait while your payment is being processed...</p>
    <?php
        $hashinput = "";
        foreach($postdata as $key => $value) {
        // create the hash input and URL leaving out any fields that have no value
        if (strlen($value) > 0) {
    ?>
        <input type="hidden" name="<?php echo($key); ?>" value="<?php echo($value); ?>"/><br>
    <?php 			
            if ((strlen($value) > 0) && ((substr($key, 0,4)=="vpc_") || (substr($key,0,5) =="user_"))) {
            $hashinput .= $key . "=" . $value . "&";
            }
        }
    }
    $hashinput = rtrim($hashinput, "&");
    ?>
	<!-- attach SecureHash -->
    <input type="hidden" name="vpc_SecureHash" value="<?php echo(strtoupper(hash_hmac('SHA256', $hashinput, pack('H*',$securesecret)))); ?>"/>
	<input type="hidden" name="vpc_SecureHashType" value="SHA256">
</form>
<script type="text/javascript">
    function send()
    {
        var f = document.getElementById("order-migs");
        f.submit();
    }
    send();
</script>